config/routes.rb
Helpmenow::Application.routes.draw do

  mount SecureResqueServer.new, :at => "/resque"
  
  get "frontpage/index"
  
  match "/notifications" => "notifications#index", :via => :post

  resources :alarms

  resources :authorisations
  
  root :to => 'frontpage#index'
end

app/models/alarm.rb
require 'resque'

class Alarm < ActiveRecord::Base
  attr_accessible :location, :phone_number, :postcode
    
  validates_format_of :phone_number,
      :message => "must be a valid UK telephone number.",
      :with => /^07[0-9]{9}$/
        
  validates_presence_of :postcode

  before_validation :convert_number, :convert_postcode
  after_create :notify_responders
  
  def convert_number
    self.phone_number = self.phone_number.gsub(/[^0-9]/, "")
  end
  
  
  def notify_responders
    Resque.enqueue(Alarm, self.id, "text_responders")
  end
  
  def text_responders
    postcode = UKPostcode.new(self.postcode)
    Authorisation.where(:postcode => postcode.outcode).each do |authorisation|
      Resque.enqueue(Authorisation, authorisation.id, "notify", self.id)
    end
  end
  
  def convert_postcode
    unless self.postcode.blank?
      postcode = UKPostcode.new(self.postcode)
      if !postcode.valid?
        self.postcode = nil
      end
    end
  end
  
  def self.queue
    :alarms
  end
  
  def self.perform(id, method, *args)
    alarm = Alarm.find(id)
    alarm.send(method, *args)
  end
  
  
end

app/models/authorisation.rb
require "messenger"
require "uk_postcode"

class Authorisation < ActiveRecord::Base
  attr_accessible :phone_number, :is_certified, :postcode
  
  validates_format_of :phone_number,
      :message => "must be a valid UK telephone number.",
      :with => /^07[0-9]{9}$/
      
  validates_uniqueness_of :phone_number  
  validates_acceptance_of :is_certified, :allow_nil=>false, :accept=>true 
  validates_presence_of :postcode
      
  before_validation :convert_number, :convert_postcode
  before_create :generate_confirmation_code
  after_create :queue_confirmation_request
  
  def self.queue
    :authorisations
  end
  
  def self.perform(id, method, *args)
    authorisation = Authorisation.find(id)
    authorisation.send(method, *args)
  end
  
  def notify(alarm_id)
    alarm = Alarm.find(alarm_id)
    Messenger.send(self.phone_number, "Alarm @ #{alarm.postcode} #{"("+alarm.location+")" unless alarm.location.blank?} - #{alarm.phone_number}")
  end
  
  def convert_number
    self.phone_number = self.phone_number.gsub(/[^0-9]/, "")
  end
  
  def convert_postcode
    unless self.postcode.blank?
      postcode = UKPostcode.new(self.postcode)
      if postcode.valid?
        self.postcode =  postcode.outcode
      else
        self.postcode = nil
      end
    end
  end
  
  def code 
    return nil
  end

  def generate_confirmation_code
    self.confirmation_code ||= OpenSSL::HMAC.hexdigest(OpenSSL::Digest::Digest.new('sha256'), ENV['HMO_SECRET'], self.phone_number+Time.now.to_s).last(5).upcase
  end
  
  def queue_confirmation_request
    Resque.enqueue(Authorisation, self.id, "send_notification_request")
  end
  
  def send_notification_request
    Messenger.send(self.phone_number, "This is your confirmation code for Help Me Now: #{self.confirmation_code}", true)
  end
end

app/models/secure_resque_server.rb
require 'resque/server'

class SecureResqueServer < Resque::Server

  use Rack::Auth::Basic, "Restricted Area" do |username, password|
    [username, password] == [ENV['RESQUE_USERNAME'], ENV['RESQUE_PASSWORD']]
  end

end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  # GET /alarms
  # GET /alarms.json
  def index
   redirect_to new_alarm_path
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
    @alarm = Alarm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alarm }
    end
  end

  # GET /alarms/new
  # GET /alarms/new.json
  def new
    @alarm = Alarm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alarm }
    end
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(params[:alarm])

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created. Responders have been notified and will call you soon. Also make sure someone actually called 999. This site is not a replacement for professional emergence services.' }
        format.json { render json: @alarm, status: :created, location: @alarm }
      else
        format.html { render action: "new" }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authorisations_controller.rb
class AuthorisationsController < ApplicationController

  def index 
    redirect_to new_authorisation_path
  end

  # GET /authorisations/new
  # GET /authorisations/new.json
  def new
    @authorisation = Authorisation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authorisation }
    end
  end  
  
  # GET /authorisations/1/edit
  def edit
    @authorisation = Authorisation.find(params[:id])
  end

  # POST /authorisations
  # POST /authorisations.json
  def create
    if authorisation = Authorisation.where("phone_number = ? AND confirmed IS NULL", params[:authorisation][:phone_number].gsub(/[^0-9]/, "")).first 
      authorisation.destroy
    end
    @authorisation = Authorisation.new(params[:authorisation])

    respond_to do |format|
      if @authorisation.save
        format.html { redirect_to edit_authorisation_path(@authorisation) }
        format.json { render json: @authorisation, status: :created, location: @authorisation }
      else
        format.html { render action: "new" }
        format.json { render json: @authorisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authorisations/1
  # PUT /authorisations/1.json
  def update
    @authorisation = Authorisation.find(params[:id])
    respond_to do |format|
      if @authorisation.confirmation_code == params[:authorisation][:code].upcase
        @authorisation.confirmed = true
        @authorisation.save
        Messenger.send(@authorisation.phone_number, "You are now setup as a 999now responder. Text STOP at any time to unsubscribe.", true)
        
        format.html { redirect_to root_url, notice: 'You are now setup as a <strong>999now</strong> responder.' }
        format.json { head :ok }
      else
        @authorisation.errors['code'] =  "is not valid."
        format.html { render action: "edit" }
        format.json { render json: @authorisation.errors, status: :unprocessable_entity }
      end
    end
  end
    # 
    # # DELETE /authorisations/1
    # # DELETE /authorisations/1.json
    # def destroy
    #   @authorisation = Authorisation.find(params[:id])
    #   @authorisation.destroy
    # 
    #   respond_to do |format|
    #     format.html { redirect_to authorisations_url }
    #     format.json { head :ok }
    #   end
    # end
end

app/controllers/frontpage_controller.rb
class FrontpageController < ApplicationController
  def index
  end

end

app/controllers/notifications_controller.rb
require "messenger"

class NotificationsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  def index
    begin
      phone_number = params[:InboundMessage][:From]
      message = params[:InboundMessage][:MessageText]
      
      raise "No message found" if message.blank?
      raise "No phone number found" if phone_number.blank?
      
      command  = message.strip.upcase
      phone_number = phone_number.gsub(/^44/, '0')
      if command == "STOP"
        authorisation = Authorisation.find_by_phone_number(phone_number)
        authorisation.destroy
        Messenger.send(phone_number, "You have now been unsubscribed from 999now.", true)
      end
    
      render :xml => {:response => {:state => 'success'}}
    rescue 
      render :xml => {:response => {:state => 'error'}}
    end
  end

end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_classes
      @body_classes ||= [controller.controller_name]
  end
end

app/helpers/authorisations_helper.rb
module AuthorisationsHelper
end

app/helpers/frontpage_helper.rb
module FrontpageHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/alarms/_form.html.erb
<%= form_for(@alarm) do |f| %>
  <% if @alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% @alarm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing alarm</h1>

<%= render 'form' %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<h1>Listing alarms</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alarms.each do |alarm| %>
  <tr>
    <td><%= alarm.location %></td>
    <td><%= alarm.phone_number %></td>
    <td><%= link_to 'Show', alarm %></td>
    <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
    <td><%= link_to 'Destroy', alarm, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>Create a new alarm</h1>

<%= form_for(@alarm) do |f| %>
  <% if @alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited this alarm from being created</h2>

      <ul>
      <% @alarm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="postcode">
    <%= f.label :postcode, "Your postcode" %>
    <%= f.text_field :postcode, :placeholder => 'loading...' %>
  </div>
  <div class="field">
    <%= f.label :location, "Any notes? (not required)" %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :phone_number, "Your phone number someone can reach you on" %>
    <%= f.text_field :phone_number, :placeholder => 'e.g. 07123456789', :type => 'tel' %>
  </div>
  <div class="actions">
    <%= link_to 'Back', root_url, :class => 'button blue'  %><%= f.submit  "Send!", :class => 'button green' %>
  </div>
<% end %>


<script>
$(document).ready(function(){
	if (Modernizr.geolocation) {
		navigator.geolocation.getCurrentPosition(prefill_location, failed_location, {maximumAge:10}) 
	}
});
</script>

app/views/application/_flash_messages.html.erb
<% if flash[:alert] || flash[:notice] %>
  <div id="notice" <% if flash[:alert] %>class="warning"<% end %>>
    <span><%= raw flash[:alert] || flash[:notice] %></span>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer>
	<strong>999now.co.uk</strong> is build by <%= link_to "Cristiano Betta", "http://cgb.im" %> with inspiration and domain by <%= link_to "Proactive Paul", "http://www.proactivepaul.com/" %>
</footer>

app/views/authorisations/_form.html.erb
<%= form_for(@authorisation) do |f| %>
  <% if @authorisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorisation.errors.count, "error") %> prohibited this authorisation from being saved:</h2>

      <ul>
      <% @authorisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number, :placeholder => "07123456789" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorisations/edit.html.erb
<h1>Step 2: <strong>Confirm</strong> your setup</h1>

<%= form_for(@authorisation) do |f| %>
	<p class='info'>We have sent you a code to confirm your phone number. Please fill in that code below and you should be all setup.</p>

  <% if @authorisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorisation.errors.count, "error") %> prohibited this authorisation from being saved:</h2>

      <ul>
      <% @authorisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code, "Confirmation code" %>
    <%= f.text_field :code, :placeholder => "e.g. AB56D" %>
  </div>
  <div class="actions">
    <%= f.submit :value => 'Confirm', :class => 'button gray' %>
  </div>
<% end %>

app/views/authorisations/index.html.erb
<h1>Listing authorisations</h1>

<table>
  <tr>
    <th>Phone number</th>
    <th>Confirmed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authorisations.each do |authorisation| %>
  <tr>
    <td><%= authorisation.phone_number %></td>
    <td><%= authorisation.confirmed %></td>
    <td><%= link_to 'Show', authorisation %></td>
    <td><%= link_to 'Edit', edit_authorisation_path(authorisation) %></td>
    <td><%= link_to 'Destroy', authorisation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authorisation', new_authorisation_path %>

app/views/authorisations/new.html.erb
<h1>Become a first responder</h1>

<%= form_for(@authorisation) do |f| %>
  <% if @authorisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorisation.errors.count, "error") %> prohibited this authorisation from being saved:</h2>

      <ul>
      <% @authorisation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number, "Your mobile phone number" %>
    <%= f.text_field :phone_number, :placeholder => "e.g. 07123456789", :type => 'tel' %>
  </div>

	<div class="field">
    <%= f.label :postcode, "Your postcode" %>
		<p>Just so we can target any requests for you.</p>
    <%= f.text_field :postcode, :placeholder => "e.g. SE1" %>
  </div>

	<div class="field inline">
    <%= f.check_box :is_certified, :value => true %>
    <%= f.label :is_certified, "I confirm that I am a qualified first aider with a current certificate" %>
  </div>

  <div class="actions">
    <%= f.submit :value => 'Continue...', :class => 'button gray' %>
  </div>
<% end %>

app/views/authorisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phone number:</b>
  <%= @authorisation.phone_number %>
</p>

<p>
  <b>Confirmed:</b>
  <%= @authorisation.confirmed %>
</p>


<%= link_to 'Edit', edit_authorisation_path(@authorisation) %> |
<%= link_to 'Back', authorisations_path %>

app/views/frontpage/index.html.erb
<p>Why wait for an ambulance if there's a first aider nearby? 999now.co.uk tries to get you a first responder as quickly as possible</p>

<%= link_to "I need help now!", alarms_path, :class => 'button red large' %>&nbsp;&nbsp;&nbsp;
<%= link_to "Become a responder", new_authorisation_path, :class => 'button blue large' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>999now - When you need a first aider.</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0,width=720px" />
</head>
<body class='<%= body_classes.join(' ') %>'>

<div id='disclaimer'><strong>999now</strong> is a proof of concept built at <a href='http://leedshack.com/'>LeedsHack 2</a> and not meant for real use<strong>!!!</strong></div>
	
<%= link_to image_tag("logo.png"), root_url, :id => 'logo' %>
<%= render :partial => 'flash_messages' %>	

<%= yield %>

<%= render :partial => 'footer' %>	


</body>
</html>

app/views/notifications/index.html.erb
<h1>Notifications#index</h1>
<p>Find me in app/views/notifications/index.html.erb</p>